### ISSUE TITLE
获取用户名失败导致脚本失效

### ISSUE THREAD

**Issue by slaier** [HaleShaw/TM-GitHubMenu#1]
```
TypeError: accountHref is undefined
    getAccountName moz-extension://f87ab634-89e4-4cd0-9164-ed55fb3355c2/GitHub菜单.user.js#1:158
    main moz-extension://f87ab634-89e4-4cd0-9164-ed55fb3355c2/GitHub菜单.user.js#1:48
    <anonymous> moz-extension://f87ab634-89e4-4cd0-9164-ed55fb3355c2/GitHub菜单.user.js#1:45
    <anonymous> moz-extension://f87ab634-89e4-4cd0-9164-ed55fb3355c2/GitHub菜单.user.js#1:216
    <anonymous> moz-extension://f87ab634-89e4-4cd0-9164-ed55fb3355c2/GitHub菜单.user.js#1:218
    <anonymous> moz-extension://f87ab634-89e4-4cd0-9164-ed55fb3355c2/GitHub菜单.user.js#1:218
```

**Comment by HaleShaw** [comment]
> ```
> TypeError: accountHref is undefined
>     getAccountName moz-extension://f87ab634-89e4-4cd0-9164-ed55fb3355c2/GitHub菜单.user.js#1:158
>     main moz-extension://f87ab634-89e4-4cd0-9164-ed55fb3355c2/GitHub菜单.user.js#1:48
>     <anonymous> moz-extension://f87ab634-89e4-4cd0-9164-ed55fb3355c2/GitHub菜单.user.js#1:45
>     <anonymous> moz-extension://f87ab634-89e4-4cd0-9164-ed55fb3355c2/GitHub菜单.user.js#1:216
>     <anonymous> moz-extension://f87ab634-89e4-4cd0-9164-ed55fb3355c2/GitHub菜单.user.js#1:218
>     <anonymous> moz-extension://f87ab634-89e4-4cd0-9164-ed55fb3355c2/GitHub菜单.user.js#1:218
> ```

Hi Slaier,
Thank for your feedback.
I actually discovered this problem a long time ago, but never had the time to fix it.😂

This is because Github enables lazy loading, and some user-related elements will not be loaded when the page is initialized. So the script can't get the account name through those elements.
Now I have fixed the problem. You can update the script to the latest version.
If you have any further questions, please contact me.
